[package]
name = "jukebox"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "jukebox"

[[bin]]
name = "tagger"

[build-dependencies]
slint-build = "1.7.2"

[dependencies]
anyhow = { version = "1.0.86" }
clap = { version = "4.5.17", features = ["derive", "env"] }
oauth2 = { version = "4.4.2", features = ["reqwest"] }
pcsc = { version = "2.8.2" }
reqwest = { version = "0.12.7", features = ["json", "blocking"] }
serde = { version = "1.0.209", features = ["derive"] }
serde_json = { version = "1.0.128" }
slint = { version = "1.7.2" }
url = { version = "2.5.2" }
