[package]
name = "jukebox"
version = "0.1.0"
edition = "2021"

[features]
ui = ["dep:slint"]

[dependencies]
anyhow = { version = "1.0.92" }
clap = { version = "4.5.17", features = ["derive", "env"] }
oauth2 = { version = "4.4.2", features = ["reqwest"] }
pcsc = { version = "2.8.2" }
rand = { version = "0.8.5" }
reqwest = { version = "0.12.7", features = ["json", "blocking"] }
serde = { version = "1.0.210", features = ["derive"] }
serde_json = { version = "1.0.128" }
slint = { version = "1.8.0", optional = true, features = ["log"] }
tracing = { version = "0.1.40" }
tracing-log = "0.2.0"
tracing-subscriber = { version = "0.3.18" }
url = { version = "2.5.2" }
