[package]
name = "jukebox"
version = "0.1.0"
edition = "2021"

[dependencies]
axum = { version = "0.7.5" }
oauth2 = { version = "4.4.2", features = ["reqwest"] }
reqwest = { version = "0.12.5", features = ["json", "blocking"] }
serde = { version = "1.0.209", features = ["derive"]}
serde_json = "1.0.92"
slint = { version = "1.7.2" }
tokio = { version = "1.38.0", features = ["full"] }
url = "2.5.2"

[build-dependencies]
slint-build = "1.7.2"