[package]
name = "jukebox"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.16", features = ["derive", "env"] }
hex = "0.4.3"
md-5 = "0.11.0-pre.4"
oauth2 = { version = "4.4.2", features = ["reqwest"] }
reqwest = { version = "0.12.5", features = ["json", "blocking"] }
rust_cast = { version = "0.19.0" }
serde = { version = "1.0.209", features = ["derive"]}
serde_json = "1.0.92"
url = "2.5.2"
humantime = "2.1.0"
