[package]
name = "jukebox"
version = "0.1.0"
edition = "2021"

[dependencies]
reqwest = { version = "0.12.5", features = ["json"] }
serde = { version = "1.0.209", features = ["derive"]}
slint = { version = "1.7.2" }
tokio = { version = "1.38.0", features = ["full"] }

[build-dependencies]
slint-build = "1.7.2"