[package]
name = "jukebox"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = { version = "1.0.86" }
clap = { version = "4.5.17", features = ["derive", "env"] }
oauth2 = { version = "4.4.2", features = ["reqwest"] }
reqwest = { version = "0.12.7", features = ["json", "blocking"] }
serde = { version = "1.0.209", features = ["derive"]}
serde_json = { version = "1.0.128" }
url = { version = "2.5.2" }
