#! /bin/bash

cargo build --release --features ui

BUNDLE="target/bundle/Jukebox.app"

rm -fr "$BUNDLE"

mkdir -p "$BUNDLE/Contents/MacOS"
mkdir -p "$BUNDLE/Contents/Resources"

cp target/release/jukebox "$BUNDLE/Contents/MacOS"
cp assets/jukebox.icns "$BUNDLE/Contents/Resources"

cat > "$BUNDLE/Contents/Info.plist" <<EOF
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>CFBundleName</key>
    <string>Jukebox</string>

    <key>CFBundleDisplayName</key>
    <string>Jukebox</string>

    <key>CFBundleIdentifier</key>
    <string>cc.salcedo.jukebox</string>

    <key>CFBundleVersion</key>
    <string>$(cargo metadata --no-deps --quiet | jq -r '.packages | last | .version')</string>

    <key>CFBundlePackageType</key>
    <string>APPL</string>

    <key>CFBundlePrimaryIconFile</key>
    <string>jukebox</string>

    <key>CFBundleIconFiles</key>
    <array>
        <string>jukebox.icns</string>
    </array>

    <key>NSHumanReadableCopyright</key>
    <string>Copyright (c) Miguel Salcedo 2024. All rights reserved.</string>

    <key>CFBundleExecutable</key>
    <string>jukebox</string>

    <key>LSEnvironment</key>
    <dict>
        <key>JUKEBOX_VERBOSITY</key>
        <string>2</string>
        <key>JUKEBOX_TOKEN_CACHE</key>
        <string>$HOME/.spotify</string>
        <key>JUKEBOX_CLIENT_ID</key>
        <string>$JUKEBOX_CLIENT_ID</string>
        <key>JUKEBOX_MARKET</key>
        <string>US</string>
        <key>JUKEBOX_DEVICE</key>
        <string>$(scutil --get ComputerName)</string>
    </dict>

    <key>LSApplicationCategoryType</key>
    <string>public.app-category.music</string>

    <key>LSFileQuarantineEnabled</key>
    <false/>

    <key>CFBundleSupportedPlatforms</key>
    <array>
        <string>MacOSX</string>
    </array>

    <key>NSHighResolutionCapable</key>
    <true/>

    <key>NSUIElement</key>
    <false/>
</dict>
</plist>
EOF