#! /bin/bash

cargo build --release --features ui

BUNDLE="target/bundle/Jukebox.app"

rm -fr "$BUNDLE"

mkdir -p "$BUNDLE/Contents/MacOS"
mkdir -p "$BUNDLE/Contents/Resources"

cp target/release/jukebox "$BUNDLE/Contents/MacOS"
cp assets/jukebox.icns "$BUNDLE/Contents/Resources"

cat > "$BUNDLE/Contents/Info.plist" <<EOF
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>CFBundleIdentifier</key>
    <string>cc.salcedo.jukebox</string>

    <key>Label</key>
    <string>cc.salcedo.jukebox</string>

    <key>CFBundleName</key>
    <string>Jukebox</string>

    <key>CFBundleShortVersionString</key>
    <string>1.0</string>

    <key>CFBundleVersion</key>
    <string>1</string>

    <key>CFBundleExecutable</key>
    <string>jukebox</string>

    <key>LSEnvironment</key>
    <dict>
        <key>JUKEBOX_VERBOSITY</key>
        <string>2</string>
        <key>JUKEBOX_TOKEN_CACHE</key>
        <string>$JUKEBOX_TOKEN_CACHE</string>
        <key>JUKEBOX_CLIENT_ID</key>
        <string>$JUKEBOX_CLIENT_ID</string>
        <key>JUKEBOX_MARKET</key>
        <string>$JUKEBOX_MARKET</string>
    </dict>

    <key>CFBundleIconFile</key>
    <string>jukebox</string>

    <key>CFBundlePrimaryIconFile</key>
    <string>jukebox</string>

    <key>NSHumanReadableCopyright</key>
    <string>Copyright (c) Miguel Salcedo 2024. All rights reserved.</string>
</dict>
</plist>
EOF