#! /bin/bash

cargo install --path "$PWD"

LAUNCH_AGENTS="$HOME/Library/LaunchAgents"
FILENAME="cc.salcedo.Jukebox.agent.plist"

AGENT_PLIST="${LAUNCH_AGENTS:?}/$FILENAME"

rm -fr AGENT_PLIST

cat > "$AGENT_PLIST" <<EOF
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>Label</key>
    <string>cc.salcedo.Jukebox</string>
    <key>ProgramArguments</key>
    <array>
        <string>$HOME/.cargo/bin/jukebox</string>
        <string>--client-id</string>
        <string>$JUKEBOX_CLIENT_ID</string>
        <string>--token-cache</string>
        <string>${JUKEBOX_TOKEN_CACHE-$HOME/.jukebox}</string>
        <string>--market</string>
        <string>${JUKEBOX_MARKET-US}</string>
        <string>--device</string>
        <string>${JUKEBOX_DEVICE-$(/usr/sbin/scutil --get ComputerName)}</string>
        <string>--address</string>
        <string>0.0.0.0:5853</string>
        <string>--local-music-path</string>
        <string>${JUKEBOX_LOCAL_MUSIC_PATH-$HOME/Music}</string>
    </array>
    <key>KeepAlive</key>
    <true/>
</dict>
</plist>
EOF

echo "Wrote agent.plist to $AGENT_PLIST"
echo "Restarting agent..."

launchctl kickstart -k gui/$(id -u)/cc.salcedo.Jukebox
