name: Tests

on:
  push:
    branches: [ main ]
    paths:
      - "Cargo.toml"
      - "Cargo.lock"
      - "src/**"
  pull_request:
    paths:
      - "Cargo.toml"
      - "Cargo.lock"
      - "src/**"
  workflow_dispatch: {}

permissions:
  contents: read

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: dtolnay/rust-toolchain@stable
      - uses: Swatinem/rust-cache@v2.9.1
      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y --no-install-recommends pkg-config libasound2-dev libpcsclite-dev
      - name: Test
        run: cargo test
